#!/bin/sh

die() {
    MSG=$1; shift
    echo "$0: $MSG" 1>&2
    exit 1
}

error() {
    MSG=$1; shift
    echo "$0: $MSG" 1>&2
    continue
}

VMIDS=

for VMNAME in "$@" ; do

    # Check the virtual machine is running
    xl list | grep -Eq "^$VMNAME\s+" \
	|| error "virtual machine '$VMNAME' is not up"

    # Save the virtual machine ID (since its name is lost while xen collecting
    # its memory back, whereas its ID is not)
    VMIDS="$VMIDS `xl domid "$VMNAME"`"

    # Shutdown the virtual machine with xl
    xl shutdown "$VMNAME" \
	>/dev/null 2>/dev/null || error "cannot shutdown '$VMNAME'"

done

# If no argument is provided, exit with an error
[ "x$VMNAME" = "x" ] && die "no virtual machine name given"

# If it were, some foreach of them, wait it is really shut down
for ID in $VMIDS ; do
    while true ; do
	xl list | awk '{print $2}' | grep -Eq "^$ID\$" || break
	sleep 1
    done
done
