#!/bin/sh

die() {
    MSG=$1; shift
    echo "$0: $MSG" 1>&2
    exit 1
}

error() {
    MSG=$1; shift
    echo "$0: $MSG" 1>&2
    [ -e "$VMDEST" ] && rm -rf "$VMDEST" 2>/dev/null
    continue
}


VMSRC=$1; shift

# Check if the source exists
[ -d "$VMSRC" ] || die "cannot find '$VMSRC'"
    

for VMDEST in "$@" ; do

    # Create the base directories
    mkdir "$VMDEST" \
	2>/dev/null || error "cannot create '$VMDEST'"


    # Perform the cheap copy of VMSRC
    mkdir "$VMDEST/mnt" || error "cannot create '$VMDEST/mnt'"
    ln "$VMSRC/initramfs.img" "$VMDEST/initramfs.img" \
	2>/dev/null || error "cannot copy ramfs"
    ln "$VMSRC/xvda1.ext4" "$VMDEST/xvda1.ext4" \
	2>/dev/null || error "cannot copy root disk"
    cp "$VMSRC/xen-config.conf" "$VMDEST/xen-config.conf" \
	2>/dev/null || error "cannot copy conf"

    # Create a new empty home
    truncate -s 1M "$VMDEST/xvda2.ext4" \
	2>/dev/null || error "cannot create home"
    yes | mkfs.ext4 "$VMDEST/xvda2.ext4" >/dev/null 2>/dev/null

    # Update the paths in xen-config.conf
    sed -ri '/^\s*ramdisk/d' "$VMDEST/xen-config.conf"
    sed -ri '/^\s*(disk|,).*xvda/d' "$VMDEST/xen-config.conf"
    sed -ri '/^\s*name/d' "$VMDEST/xen-config.conf"

    (
	echo "ramdisk = \"`realpath $VMDEST/initramfs.img`\""
	echo "name = \"$VMDEST\""
	echo "disk = [\"`realpath $VMDEST/xvda1.ext4`,raw,xvda1,r\""
	echo "       ,\"`realpath $VMDEST/xvda2.ext4`,raw,xvda2,rw\"]"
    ) >>"$VMDEST/xen-config.conf"
done

[ "x$VMDEST" = "x" ] && die "no destination specified"
exit 0
